# Generated by Django 6.1.1 on 2026-10-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='booking_status',
            field=models.BooleanField(default=False),
        ),
    ]
