# Generated by Django 6.1.1 on 2026-10-08 04:13

from django.db import migrations

def add_seats(apps, schema_editor):
    Seat = apps.get_model("bookings", "Seat")
    seat_num = 1
    while seat_num <= 15:
        Seat.objects.create(seat_number = seat_num, booking_status = False)
        seat_num += 1

class Migration(migrations.Migration):
    dependencies = [
        ('bookings', '0003_alter_booking_user'),
    ]

    operations = [
         migrations.RunPython(add_seats),
    ]
